# Generated by Django 2.0.7 on 2018-07-25 12:54

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='geom',
            field=djgeojson.fields.PointField(default=0),
            preserve_default=False,
        ),
    ]
