# Generated by Django 2.0.7 on 2018-07-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_marker_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='geom',
        ),
    ]
