# Generated by Django 2.0.7 on 2018-07-25 20:15

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_marker_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='link',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='lon',
        ),
        migrations.AddField(
            model_name='marker',
            name='address',
            field=django_google_maps.fields.AddressField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
